Repository tanaypratap/teamtanay.jobchallenge.dev, pull requests merged in 2020-04, with the labels that each got.

#314 registering devansh
  content/participants/ttjc@devansh5/index.md
Labels: good-to-merge

#318 Added First Project
  content/participants/ttjc@SudhanshuMishra8826/index.md
Labels: good-to-merge

#323 registering gokintosh
  content/participants/ttjc@gokintosh/index.md
Labels: good-to-merge

#324 registering for the challenge
  content/participants/ttjc@shanudjn/index.md
Labels: good-to-merge

#327 Adding portfolio Link
  content/participants/ttjc@chintankamani/index.md
Labels: good-to-merge

#330 Registering in Job Challenge
  content/participants/ttjc@kaushalkoladiya/index.md
Labels: good-to-merge

#92 Adding terms and conditions
  content/faq/12_terms_and_conditions/index.md
  content/faq/13_Privacy_Policy/index.md
Labels: tanay-take-a-look

#338 registering gauravsomani336
  content/participants/ttjc@gauravsomani336/index.md
Labels: good-to-merge

#341 Astron98/registration update
  content/participants/ttjc@astron98/index.md
Labels: good-to-merge

#337 one project added
  content/participants/ttjc@ooreally/index.md
Labels: issue-commiter-correction

#346 Adding Mentors Bio
  content/mentors_bio/Ameer_Jhan/index.md
  content/mentors_images/ameer_jhan.jpg
Labels: tanay-take-a-look

#350 registering blazephoenix
  content/participants/ttjc@blazephoenix/index.md
Labels: good-to-merge

#353 registering ayushpaharia
  content/participants/ttjc@ayushpaharia/index.md
Labels: good-to-merge

#355 registering Shivraj97
  content/participants/ttjc@Shivraj97/index.md
Labels: good-to-merge

#356 Registering md-yaseen
  content/participants/ttjc@md-yaseen/index.md
Labels: good-to-merge

#361 Create ttjc@anwesha999 index.md
  content/participants/ttjc@anwesha999/index.md
Labels: good-to-merge

#366 registering duhbhavesh
  content/participants/ttjc@duhbhavesh/index.md
Labels: good-to-merge

#369 My Entry
  content/participants/ttjc@ShravanMeena/index.md
Labels: good-to-merge

#374 Registering Rushikesh Chaudhari
  content/participants/ttjc@RushikeshChaudhari/index.md
Labels: good-to-merge

#375 registering ayush909
  content/participants/ttjc@Ayush909/index.md
Labels: good-to-merge

#376 Registering parimalnajan
  content/participants/ttjc@parimalnajan/index.md
Labels: good-to-merge

#388 registering urmilbhatt
  content/participants/ttjc@urmilbhatt/index.md
Labels: good-to-merge

#382 I accept the challenge 🎉
  content/participants/ttjc@heyayushh/index.md
Labels: good-to-merge

#371 registering demo-participant
  content/participants/ttjc@priyanshuvaya/index.md
Labels: issue-commiter-correction

#404 Create index.md
  content/participants/ttjc@divyanshi-agr/index.md
Labels: good-to-merge

#436 registering shubhamchopade
  content/participants/ttjc@shubhamchopade/index.md
Labels: dikkat-hi-dikkat
