Repository tanaypratap/teamtanay.jobchallenge.dev, pull requests merged in 2020-03, with the labels that each got.

#6 pravesh18/registration-update
  content/participants/ttjc@pravesh18/index.md
Labels: good-to-merge

#7 Registration/knowsach
  content/participants/ttjc@knowsach/index.md
Labels: good-to-merge

#9 registering chintankamani
  content/participants/ttjc@chintankamani/index.md
Labels: good-to-merge

#10 Dikshagoyal26/registration update
  content/participants/ttjc@dikshagoyal26/index.md
Labels: good-to-merge

#12 Registering vinod2305
  content/participants/ttjc@vinod2305/index.md
Labels: good-to-merge, issue-commiter-correction, issue-resolved

#54 registration for rehasantiago
  content/participants/ttjc@rehasantiago/index.md
Labels: good-to-merge

#56 Registration update
  content/participants/ttjc@Pkpratik/index.md
Labels: good-to-merge

#58 Registering ProgrammerAvinash
  content/participants/ttjc@ProgrammerAvinash/index.md
Labels: good-to-merge

#81 Sudharsan GS registration
  content/participants/ttjc@sudharsangs/index.md
Labels: good-to-merge

#45 registering namancdr
  content/participants/ttjc@namancdr/index.md
Labels: good-to-merge, issue-commiter-correction, issue-resolved

#11 Registration PR Kanishk Gupta
  content/participants/ttjc@gkanishk/index.md
Labels: good-to-merge, review-by-author

#62 registering tridibsamanta
  content/participants/ttjc@tridibsamanta/index.md
Labels: good-to-merge

#50 Ayan Shukla Registerting
  content/participants/ttjc@Ayan4/index.md
Labels: good-to-merge

#69 Registering Arab Kumar
  content/participants/ttjc@KumarArab/index.md
Labels: good-to-merge

#67 Anasyahiya/registration update
  content/participants/ttjc@anasyahiya/index.md
Labels: good-to-merge

#66 My registration - tejasa97
  content/participants/ttjc@tejasa97/index.md
Labels: good-to-merge

#64 Registration : Harshavardhan pb
  content/participants/ttjc@harshbisle/index.md
Labels: good-to-merge

#52 registration update for globefire
  content/participants/ttjc@globefire/index.md
Labels: good-to-merge

#47 Khusharth/registration update
  content/participants/ttjc@khusharth/index.md
Labels: good-to-merge

#13 registering Yogesh Bhatt
  content/participants/ttjc@yogesh-hackx/index.md
Labels: good-to-merge

#14 registering cdking007
  content/participants/ttjc@cdking007/index.md
Labels: good-to-merge

#15 registering Swapnadeep Mohapatra
  content/participants/ttjc@swapnadeepmohapatra/index.md
Labels: good-to-merge

#17 registering for job challenge
  content/participants/ttjc@razi1998/index.md
Labels: good-to-merge

#19 My entry for the challenge.
  content/participants/ttjc@manan2002/index.md
Labels: good-to-merge

#20 registering as a participant
  content/participants/ttjc@iamkunall/index.md
Labels: good-to-merge

#21 my registration
  content/participants/ttjc@HemendraKhatik/index.md
Labels: good-to-merge

#23 Registering Neeraj
  content/participants/ttjc@neerajs296/index.md
Labels: good-to-merge

#24 Registation/SudhanshuMishra8826
  content/participants/ttjc@SudhanshuMishra8826/index.md
Labels: good-to-merge

#25 Participation Form - Vikrant Bhat
  content/participants/ttjc@bhatvikrant/index.md
Labels: good-to-merge

#26 Vishavjeet branch
  content/participants/ttjc@Vishavjeet6/index.md
Labels: good-to-merge

#27 Saksham Kapur Registration
  content/participants/ttjc@Sakshamkapur/index.md
Labels: good-to-merge

#22 registration
  content/participants/ttjc@JatinRanka/index.md
Labels: good-to-merge

#28 Registration from sumit
  content/participants copy/ttjc@sumit121dev/index.md
Labels: good-to-merge

#29 Registration PR
  content/participants/ttjc@rahulbakshi4/index.md
Labels: good-to-merge

#31 Add geekysrm
  content/participants/ttjc@geekysrm/index.md
Labels: good-to-merge

#32 Registration/NikhilNamal17
  content/participants/ttjc@NikhilNamal17/index.md
Labels: good-to-merge

#34 registering ujjwal maurya
  content/participants/ttjc@Ujjwal-here/index.md
Labels: good-to-merge

#33 registering haldersubhro
  content/participants/ttjc@haldersubhro/index.md
Labels: good-to-merge

#35 digvijaysrathore Registration
  content/participants/ttjc@digvijaysrathore/index.md
Labels: good-to-merge

#36 registering lakshay
  content/participants/ttjc@Lakshay-Batra/index.md
Labels: good-to-merge

#37 registering for Uttkarsh-Srivastava
  content/participants/ttjc@Uttkarsh-Srivastava/index.md
Labels: good-to-merge

#38 Sruthiragupathy/registration update
  content/participants/ttjc@sruthiragupathy/index.md
Labels: good-to-merge

#39 registering TussharLaddha
  content/participants/ttjc@tusshar2000/index.md
Labels: good-to-merge

#40 Participation aditya-raj
  content/participants/ttjc@Aadi-27/index.md
Labels: good-to-merge

#41 registering 4k45hv3rm4
  content/participants/ttjc@4k45hv3rm4/index.md
Labels: good-to-merge

#42 registration ItachiHyuga
  content/participants/ttjc@ItachiHyuga/index.md
Labels: good-to-merge

#44 Registering Vinit Raut
  content/participants/ttcj@vin18/index.md
Labels: good-to-merge

#95 Demoparticipant/registration update
  content/participants/ttjc@Cvmsingh/index.md
Labels: good-to-merge

#46 Registered for the challenge
  content/participants/ttjc@Aravindan07/index.md
Labels: good-to-merge

#49 Registration/rishabhkanojiya
  content/participants/ttjc@rishabhkanojiya/index.md
Labels: good-to-merge

#48 Registering Mihir
  content/participants/ttjc@mihirgupta0900/index.md
Labels: good-to-merge

#63 Registering Omkar.
  content/participants/ttjc@OmkarGeedh/index.md
Labels: good-to-merge

#80 registeringAmarKumar
  content/participants/ttjc@amarcahturvedi16/index.md
Labels: good-to-merge

#130 registering megha-pathak
  content/participants/ttjc@Megha-Pathak/index.md
Labels: review-pending

#65 Registering Mritunjay Saha
  content/participants/ttjc@mritunjaysaha/index.md
Labels: good-to-merge

#129 Registering Srihari44
  content/participants/ttjc@srihari44/index.md
Labels: review-pending

#131 Registration rahul ravindran
  content/participants/ttcj@rahul1116/index.md
Labels: good-to-merge

#132 Registering kumaraswamy
  content/participants/ttjc@kumaraswamy1/index.md
Labels: good-to-merge

#133 Registering Yogesh Yadav
  content/participants/ttjc@yogesh-io/index.md
Labels: good-to-merge

#135 registering PremKantikar
  content/participants/ttjc@premkantikar/index.md
Labels: good-to-merge

#140 Registering Sandeep Ashok
  content/participants/ttjc@sandeepashok/index.md
Labels: good-to-merge

#109 Kousik Chandra Application
  content/participants/ttjc@KousikTheHunk/index.md
Labels: good-to-merge

#85 My aaplication
  content/participants/ttjc@KousikTheHunk/index.md
Labels: submitted-after-deadline

#110 Registering nerdgaurish for challenge
  content/participants/ttjc@nerdgaurish/index.md
Labels: good-to-merge

#111 Mannypanwar registration
  content/participants/ttjs@mannypanwar/index.md
Labels: good-to-merge

#112 registering Himanshu916
  content/participants/ttjc@Himansh916/index.md
Labels: good-to-merge

#89 registering Himanshu916
  content/participants/ttjc@Himansh916/index.md
Labels: submitted-after-deadline

#128 Registering Sai Karthik P
  content/participants/ttjc@sai-karthik-p/index.md
Labels: good-to-merge

#126 registration for ttjc
  content/participants/ttjc@DeveloperOps/index.md
Labels: good-to-merge

#125 adding varenAggarwal
  content/participants/ttjc@varenaggarwal/index.md
Labels: good-to-merge

#124 registering chandanbreddy
  content/participants/ttjc@chandanbreddy/index.md
Labels: good-to-merge

#123 registrating tapanchudasama
  content/participants/ttjc@inflame07/index.md
Labels: good-to-merge

#113 Kartikeyyadav/registration update
  content/participants/ttjc@Kartikeyyadav7/index.md
Labels: good-to-merge

#115 GurpreetSingh/registration update
  content/participants/ttjc@GurpreetSinghPruthi/index.md
Labels: good-to-merge

#116 registering: Harshita Ramchandani
  content/participants/ttjc@HARSHI28A/index.md
Labels: good-to-merge

#114 registering Uyadav207
  content/participants/ttjc@Uyadav207/index.md
Labels: good-to-merge

#86 registering Uyadav207
  content/participants/ttjc@Uyadav207/index.md
Labels: submitted-after-deadline

#117 registering vivek0330
  content/participants/ttjc@vivek0330/index.md
Labels: good-to-merge

#118 afrazchelsea/registration update2
  content/participants/ttjc@afrazchelsea/index.md
Labels: good-to-merge

#119 registering anand-developer
  content/participants/ttjc@developer-anand/index.md
Labels: good-to-merge

#120 Registering as Anmol Chaudhary
  content/participants/ttjc@4nmolChaudhary/index.md
Labels: good-to-merge

#122 Registration update
  content/participants/ttjc@mallikarjun2000/index.md
Labels: good-to-merge

#121 Ashish0077/registration update
  content/participants/ttjc@Ashish0077/index.md
Labels: good-to-merge

#142 Registering callmehickey
  content/participants/ttcj@callmehickey/index.md
Labels: good-to-merge

#162 registering shoaibsayyed
  content/participants/ttjc@shoaibsayyed/index.md
Labels: good-to-merge

#164 we need more peoples like you
  content/participants/ttjc@dhruvSHA256/index.md
Labels: good-to-merge

#163 Registering for the challenge.
  content/participants/ttjc@ArsharajChauhan/index.md
Labels: good-to-merge

#154 registering as participant
  content/participants/ttjc@rutikwankhade/index.md
Labels: good-to-merge

#153 registering Poonam Mohata
  content/participants/ttjc@poonammohata/index.md
Labels: good-to-merge

#147 Participation Application
  content/participants/ttcj@guptavarun619/index.md
Labels: good-to-merge

#141 registring altaf shaikh
  content/participants/ttjc@altaf99/index.md
Labels: good-to-merge

#145 Registration Nitesh Narang
  content/participants/ttjc@theniteshnarang/index.md
Labels: issue-commiter-correction

#157 Registration For the Challenge
  content/participants/ttjc@Deepansharora27/index.md
Labels: issue-commiter-correction

#144 Registration Submission Bharath Adhikari
  content/participants/ttcj@Adhikaribharath/index.md
Labels: issue-commiter-correction

#127 Developer anand/registration update
  content/participants/ttjc@developer-anand/index.md
Labels: issue-commiter-correction

#61 Registering Afroz Quraishi
  content/participants/ttjc@afroz23/index.md
Labels: issue-commiter-correction

#136 registering devowolf
  content/participants/ttjc@devowolf/index.md
Labels: good-to-merge

#76 Registration request for teamtanayjobchallenge from RahulChugwani
  content/participants/ttjc@RahulChugwani/index.md
Labels: issue-commiter-correction

#134 Registering virensuthar
  content/participants/ttjc@virensuthar/index.md
Labels: issue-commiter-correction

#73 registering sujoys10
  content/participants/ttjc@sujoys10/index.md
Labels: submitted-after-deadline

#160 Registering Tejas H N
  content/participants/ttjc@hntejas/index.md
Labels: issue-commiter-correction

#165 Corrected Markdown and made some changes
  content/participants/ttjc@iManmeetKaur/index.md
Labels: review-pending

#166 Registering Rickey07
  content/participants/ttjc@Rickey07/index.md
Labels: review-pending

#167 participating PratikKumarSingh
  content/participants/ttcj@singh-pk/index.md
Labels: good-to-merge

#168 Register as new Participant
  content/participants/ttjc@vishalsingla34-coder/index.md
Labels: review-pending

#149 Register Participant
  content/participants/ttjc@vishalsingla34-coder/index.md
Labels: issue-commiter-correction

#169 Create index.md
  content/participants/ttjc@AnushkaRaj/index.md
Labels: review-pending

#170 registering optimusrahul
  content/participants/ttjc@OptimusRahul/index.md
Labels: good-to-merge

#171 Ankita1996/registrationAnkita
  content/participants/ttjc@Ankita1996/index.md
Labels: good-to-merge

#176 regitering kodurivamshi
  content/participants/ttjc@kodurivamshi/index.md
  package-lock.json
  package.json
Labels: good-to-merge

#143 Registering Viral Sangani
  content/participants/ttcj@viral-sangani/index.md
Labels: issue-commiter-correction

#183 registering meghnavarma0
  content/participants/ttjc@meghnavarma0/index.md
Labels: good-to-merge

#185 index.md
  content/participants/ttjc@rumishra/index.md
Labels: issue-commiter-correction

#71 Registering Anirudh Jwala
  content/participants/ttjc@anirudh-jwala/index.md
Labels: submitted-after-deadline

#84 here I am making a pull request
  content/participants/ttjc@tanaypratap/participants/ttjc@gitarthakashyap/index.md
Labels: good-to-merge

#97 Registering for Job Challenge/Rohit Giri
  content/participants/ttjc@rgiri1706/index.md
Labels: good-to-merge

#96 registering farhxnbaig
  content/participants/ttjc@farhxnbaig/index.md
Labels: good-to-merge

#88 Registering Aarti Gurjar
  content/participants/ttjc@aartigurjar/index.md
Labels: good-to-merge

#78 registering bhupesh-v
  content/participants/ttjc@bhupesh-v/index.md
Labels: good-to-merge

#175 Demoparticipant/registration update
  content/participants/ttjc@Rishabh4991/index.md
Labels: issue-commiter-correction

#161 Registering Aditya Pratap
  content/participants/ttjc@apshada/index.md
Labels: good-to-merge

#189 registering AshKemp
  content/participants/ttjc@AshKemp/index.md
Labels: review-pending

#190 registering utkarsh-srivastava
  content/participants/ttjs@utkarsh-srivastava/index.md
Labels: good-to-merge

#191 resolving commiter-error
  content/participants/ttcj@vismitap/index.md
Labels: good-to-merge

#192 registering adithyanarayana
  content/participants/ttjc@adithyanarayana/index.md
Labels: good-to-merge

#193 Registering Abhinav Reddy
  content/participants/ttjc@singularityDev/index.md
Labels: good-to-merge

#194 TechTarun registration
  content/participants/ttjc@TechTarun/index.md
Labels: good-to-merge

#195 registering suryanshsugandhi
  content/participants/ttjc@suryanshsugandhi/index.md
Labels: good-to-merge

#197 registering mayank
  content/participants/ttjc@mayankgoel871/index.md
Labels: good-to-merge

#198 registering Mohammed hussam khatib
  content/participants/ttjc@hussamkhatib/index.md
Labels: good-to-merge

#199 registering muhib
  content/participants/ttcj@Muhib007dev/index.md
Labels: good-to-merge

#172 Registering Aniket Chaudhari
  content/participants/ttjc@aniketchaudhari3/index.md
Labels: issue-commiter-correction, tanay-take-a-look

#79 Adding FAQ 32 to 42
  content/faq/32_how-to-know-if-my-registration-is-successful/index.md
  content/faq/33_how-to-know-if-there-are-problems-in-my-registration-pr/index.md
  content/faq/34_how-often-should-i-push-my-changes/index.md
  content/faq/35_projects-using-the-same-domain-stack/index.md
  content/faq/37_how-to-showcase-well-rounded-profile-of-projects/index.md
  content/faq/38_are-group-projects-allowed/index.md
  content/faq/39_how-is-this-going-to-be-beneficial-for-a-beginner/index.md
  content/faq/40_what-if-i-dont-win-this-challenge/index.md
  content/faq/41_what-if-i-could-not-find-anyone-for-review/index.md
  content/faq/42_cost-to-participate-in-the-challenge/index.md
Labels: tanay-take-a-look

#196 Registering malhotra-parul
  content/participants/ttjc@malhotra-parul/index.md
Labels: good-to-merge

#173 registering panchami6
  content/participants/ttjc@panchami6/index.md
Labels: good-to-merge

#202 Registering Harshitha for #TeamTanay Challenge
  content/participants/ttjc@HarshithaSolai/index.md
Labels: good-to-merge

#159 for the registration
  content/participants/ttjc@prernamehraa/index.md
Labels: issue-commiter-correction

#148 Registration is complete.Looking forward for your response.
  content/participants/ttjc@sarulathadurai/index.md
Labels: issue-commiter-correction

#146 Registering Sushil Buragute
  content/participants/ttjc@sushilburagute/index.md
Labels: good-to-merge

#138 Create index.md
  content/participants/ttjc@developer-anand/index.md
Labels: issue-commiter-correction

#152 Registering myself as a Participant
  content/participants/ttjc@piyush-mahapatra-au6/index.md
Labels: issue-commiter-correction

#55 registering thusharsreenivas
  content/participants/ttjc@Thushar-Sreenivas/index.md
Labels: issue-commiter-correction

#107 Registring Aditya Sharan
  content/participants/ttjc@adityasharan01/index.md
Labels: good-to-merge

#158 registering ishita
  content/participants/ttjc@ishita1608/index.md
Labels: good-to-merge

#174 Asmit shrivastava
  content/participants/ttjc@asmitzz/index.md
Labels: issue-commiter-correction

#70 registering TheDemonDante
  content/participants/index.md
Labels: good-to-merge

#210 registering prateek saini
  content/participants/ttjc@prateek1998/index.md
Labels: good-to-merge

#214 Renamed Participants directory name
  content/participants/ttjc@Adhikaribharath/index.md
  content/participants/ttjc@Muhib007dev/index.md
  content/participants/ttjc@callmehickey/index.md
  content/participants/ttjc@guptavarun619/index.md
  content/participants/ttjc@rahul1116/index.md
  content/participants/ttjc@singh-pk/index.md
  content/participants/ttjc@vin18/index.md
  content/participants/ttjc@viral-sangani/index.md
  content/participants/ttjc@vismitap/index.md
Labels: tanay-take-a-look

#211 Faq 2 registration
  content/assets/reg1-open-desktop.png
  content/assets/reg10-error-1.png
  content/assets/reg2-folder.png
  content/assets/reg3-projects.png
  content/assets/reg4-blogs.png
  content/assets/reg5-commit.png
  content/assets/reg6-publish.png
  content/assets/reg7-compare-and-pull.png
  content/assets/reg8-pull.png
  content/assets/reg9-deploy.png
  content/faq/01_who-can-participate/index.md
  content/faq/02_is-registration-required/index.md
  content/faq/06_how-to-get-reviews/index.md
Labels: tanay-take-a-look

#215 Registration Priyansh shukla
  content/participants/ttjc@priyanshps/index.md
Labels: good-to-merge
