Repository tanaypratap/teamtanay.jobchallenge.dev, pull requests merged in 2020-05, with the labels that each got.

#447 Registering vedantk21
  content/participants/ttjc@vedantk21/index.md
Labels: good-to-merge

#438 registering ishita303
  content/participants/ttjc@ishita303/index.md
Labels: dikkat-hi-dikkat

#437 Added FAQ no. 49
  content/faq/49_are-we-going-to-get-a-job-offer/index.md
Labels: good-to-merge

#476 Registered myself
  content/participants/ttjc@knightcube/index.md
Labels: dikkat-hi-dikkat

#492 Registering rachit
  content/participants/ttjc@rachitg001/index.md
Labels: good-to-merge

#509 Added registration deadline
  content/main/about-team-tanay/index.md
  content/main/challenge-details/index.md
  src/pages/index.js
Labels: tanay-take-a-look

#525 registering rahulbhatt1899
  content/participants/ttjc@rahulbhatt1899/index.md
Labels: good-to-merge

#607 Registering saifeemustafaq
  content/participants/ttjc@saifeemustafaq/index.md
Labels: dikkat-hi-dikkat

#487 Registration for job Challenge
  content/participants/ttjc@Its-Shashank/index.md
Labels: dikkat-hi-dikkat

#619 Simscool1/registration update
  content/participants/ttjc@simscool1/index.md
Labels: dikkat-hi-dikkat

#654 registering sidrakshe28
  content/participants/ttjc@sidrakshe28/index.md
Labels: dikkat-hi-dikkat

#598 Shivraj97/Updated index.md and added link to blogs
  content/participants/ttjc@Shivraj97/index.md
Labels: dikkat-hi-dikkat

#691 registering jittash
  content/participants/ttjc@jittash/index.md
Labels: dikkat-hi-dikkat

#682 My intro
  content/participants/Index.md
Labels: dikkat-hi-dikkat

#615 Displaying number of participants
  src/components/layout.js
  src/pages/participants.js
Labels: review-pending
