Repository tanaypratap/teamtanay.jobchallenge.dev, pull requests merged in 2020-06, with the labels that each got.

#696 registering for job challenge
  content/participants/ttjc@konnster99/index.md
Labels: dikkat-hi-dikkat

#766 registering Harshit Bharani
  content/participants/ttjc@HarshitBharani/index.md
Labels: dikkat-hi-dikkat

#744 registering hardikchoudhary20
  content/participants/ttjc@hardikchoudhary20/index.md
Labels: dikkat-hi-dikkat

#740 registering demo participant
  content/participants/ttjc@AbhishekkGautam/index.md
Labels: dikkat-hi-dikkat

#737 registering Ayush Goel(ayush2609)
  content/participants/ttjc@ayush2609/index.md
Labels: dikkat-hi-dikkat

#724 Register Purva Sheth
  content/participants/ttjc@purvasheth/index.md
Labels: dikkat-hi-dikkat

#720 registering participant
  content/participants/ttjc@Harshita-Kanal/index.md
Labels: dikkat-hi-dikkat

#736 registering demoparticipant
  content/participants/ttjc@gauravmishra-17/index.md
Labels: dikkat-hi-dikkat

#762 Rohankokane/registration update
  content/participants/ttjc@rohankokane/index.md
Labels: dikkat-hi-dikkat

#664 Project and blogs update
  content/participants/ttjc@tarunyadav1/index.md
Labels: dikkat-hi-dikkat

#770 registering bhavika022
  content/participants/ttjc@bhavika022/index.md
Labels: submitted-after-deadline

#771 registering gourishankar27
  content/participants/ttjc@gourishankar27/index.md
Labels: submitted-after-deadline

#775 registering vinamra-jain
  content/participants/ttjc@vinamra-jain/index.md
Labels: submitted-after-deadline

#763 registaring Yash Soni
  content/participants/ttjc@mryashsoni/index.md
Labels: dikkat-hi-dikkat

#783 Saiteja bma/registration update fixed
  content/participants/ttjc@saiteja-bma/index.md
Labels: good-to-merge

#824 Updated Projects List
  content/participants/ttjc@skadewdle/index.md
Labels: good-to-merge

#575 registering aaquibparticipant
  content/participants/ttjc@killcodeX/index.md
Labels: dikkat-hi-dikkat

#898 Syedsufiyan/ portfolio
  content/participants/ttjc@thesyedsufiyan/index.md
Labels: dikkat-hi-dikkat

#915 Project 5-Update-ExpenseTracker-Angular
  content/participants/ttjc@Harshi7016/index.md
Labels: dikkat-hi-dikkat

#928 Updating Index.md
  content/participants/ttjc@apshada/index.md
Labels: completed 5P3B

#949 Profile updation with 5 projects and 3 blogs
  content/participants/ttjc@yashraj2312/index.md
Labels: completed 5P3B

#1008 final submission
  content/finalist/ttjc@abhishek-031/index.md
Labels: the finalist
