Repository tanaypratap/teamtanay.jobchallenge.dev, pull requests merged in 2020-07, with the labels that each got.

#994 Update index.md
  content/participants/ttjc@duhbhavesh/index.md
Labels: completed 5P3B

#1013 Finalist entry
  content/finalist/ttjc@duhbhavesh/index.md
Labels: the finalist

#1018 Optimusrahul/registration update
  content/participants/ttjc@OptimusRahul/index.md
Labels: completed 5P3B

#914 first project updated- uiGeneratorkit
  content/participants/ttjc@karthikraji2020/index.md
Labels: dikkat-hi-dikkat

#569 Shoaibsayyed/Updated Profile
  content/participants/ttjc@shoaibsayyed/index.md
Labels: dikkat-hi-dikkat

#1064 added image link and updated directory name
  content/finalist/ttjc@abhishek-031/index.md
  content/finalist/ttjc@finalist@abhishek-031/index.md
Labels: review-pending

#1047 Projects completed
  content/participants/ttjc@Manoj-M-S/index.md
Labels: review-pending

#1071 Updated demo + image
  content/finalist/ttjc@Megha-Pathak/index.md
  content/finalist/ttjc@finalist@Megha-Pathak/index.md
Labels: dikkat-hi-dikkat

#1093 Image-link update
  content/finalist/ttjc@finalist@4k45hv3rm4/index.md
Labels: review-pending

#1108 Profile Picture added (finalist)
  content/finalist/ttjc@finalist@tarunyadav1/index.md
Labels: dikkat-hi-dikkat

#1109 Completing the challenge
  content/finalist/ttjc@finalist@dikshagoyal26/index.md
Labels: dikkat-hi-dikkat

#1105 challenge completed
  content/finalist/ttjc@finalist@nawaz0002/index.md
Labels: review-pending
